// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsaMQ23Mjt2Tl-Lbq0NGNadehDtBHkg6g',
    appId: '1:106497067474:web:8f3b3648ef8d8a4a33200b',
    messagingSenderId: '106497067474',
    projectId: 'fristfix-app',
    authDomain: 'fristfix-app.firebaseapp.com',
    storageBucket: 'fristfix-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqO9U0dUlZUIpBH-YC5lOOdMXPkANpP8Q',
    appId: '1:106497067474:android:5c4470f20019f39a33200b',
    messagingSenderId: '106497067474',
    projectId: 'fristfix-app',
    storageBucket: 'fristfix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6q4n3NPOc5Jw6IKF-y13PVVb7T8cZnA',
    appId: '1:106497067474:ios:35f5ec83209da16d33200b',
    messagingSenderId: '106497067474',
    projectId: 'fristfix-app',
    storageBucket: 'fristfix-app.firebasestorage.app',
    androidClientId: '106497067474-dq21dpetrgap9og3ops92p1f718m6qoq.apps.googleusercontent.com',
    iosClientId: '106497067474-l9qeho7c79dfeeaoit48k7g1iepram5s.apps.googleusercontent.com',
    iosBundleId: 'de.fristfix.fristfix',
  );

}